"""Enumerate legal task checkpoints into a frozen GRPO train/eval suite.

Every checkpoint is a replayable prefix of valid actions plus one executable
reference action. Prefixes are generated by breadth-first search over the real
environment, so a checkpoint cannot encode an unreachable state.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from characore.agent import DeliveryTask, TASK_ID, command, dump, messages
from characore.grpo_rewards import REWARD_SPEC, restore, transition
from characore.judge_runner import identity
from characore.protocol import digest

# The full legal action space at any checkpoint; the search filters by preconditions.
ACTIONS = [
    command("inspect_clue", clue_id="dispatch"),
    command("inspect_clue", clue_id="route"),
    command("query_status"),
    command("submit_action", action="promise", promise="keep_sealed"),
    command("submit_action", action="move", route="north"),
    command("submit_action", action="deliver"),
]


def successors(prefix):
    """Actions that execute successfully and leave the task active."""
    out = []
    for raw in ACTIONS:
        env = DeliveryTask()
        try:
            for earlier in prefix:
                env.step(earlier)
            row = env.step(raw)
        except ValueError:
            continue
        if not row["failure"] and env.state["status"] == "active":
            out.append(raw)
    return out


def choose_anchor(prefix, options):
    """Prefer a legal action that advances state, so the reference is not a no-op.

    This is a comparison baseline for pairwise judging, never a gold label: the
    policy can legitimately be scored above it.
    """
    for raw in options:
        if transition(prefix, raw)[2]:
            return raw
    return options[0]


def enumerate_checkpoints(max_depth):
    """BFS over reachable nonterminal states, deduplicated by visible observation."""
    found, seen, frontier = [], set(), [[]]
    while frontier:
        prefix = frontier.pop(0)
        if len(prefix) >= max_depth:
            continue
        options = successors(prefix)
        if not options:
            continue
        signature = identity(messages(restore(prefix).observation()))
        if signature not in seen:
            seen.add(signature)
            found.append(dict(prefix=list(prefix), anchor=choose_anchor(prefix, options),
                              depth=len(prefix), legal_actions=len(options)))
        for raw in options:
            frontier.append(prefix + [raw])
    return found


def build(output, max_depth, eval_count, reviewer):
    checkpoints = enumerate_checkpoints(max_depth)
    if len(checkpoints) <= eval_count:
        raise ValueError("not enough distinct checkpoints for a train/eval split")
    ordered = sorted(checkpoints, key=lambda c: (c["depth"], c["anchor"]))
    # Take eval checkpoints one per depth, deepest depths last. Proportional
    # sampling would put nearly all of them at the deepest level, because the
    # state tree fans out; one per depth keeps early decisions in the split too.
    by_depth = {}
    for index, item in enumerate(ordered):
        by_depth.setdefault(item["depth"], []).append(index)
    picked, depths = [], sorted(by_depth)
    while len(picked) < eval_count:
        room = [d for d in depths if len(by_depth[d]) > 1]
        if not room:
            raise ValueError("not enough distinct checkpoints for a train/eval split")
        for depth in room:
            if len(picked) == eval_count:
                break
            picked.append(by_depth[depth].pop(len(by_depth[depth]) // 2))
    picked = set(picked)
    holdout = [ordered[i] for i in sorted(picked)]
    training = [c for i, c in enumerate(ordered) if i not in picked]
    rows = {}
    for split, items in (("train", training), ("eval", holdout)):
        rows[split] = [
            dict(id=f"{split}_{number:03d}", split=split, exposure="development",
                 family=TASK_ID, source=TASK_ID, prefix=item["prefix"], anchor=item["anchor"])
            for number, item in enumerate(items, 1)
        ]
    output.mkdir(parents=True, exist_ok=False)
    for split in ("train", "eval"):
        dump(output / f"{split}.json", rows[split])
    dump(output / "freeze.json", dict(
        task_id=TASK_ID, evaluation_scope="development_only",
        reward_spec_sha256=identity(REWARD_SPEC), created_by=reviewer,
        files={name: digest(output / name) for name in ("train.json", "eval.json")},
        claim="Development checkpoints from one authored task family; not an independent holdout."))
    return {split: len(rows[split]) for split in rows}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--max-depth", type=int, default=5)
    parser.add_argument("--eval-count", type=int, default=4)
    parser.add_argument("--created-by", default="build_agent_suite")
    args = parser.parse_args()
    if args.max_depth < 1 or args.eval_count < 1:
        parser.error("max-depth and eval-count must be positive")
    counts = build(args.output, args.max_depth, args.eval_count, args.created_by)
    print(json.dumps(dict(**counts, scope="development_only"), ensure_ascii=False))


if __name__ == "__main__":
    main()
